// Package scenario defines the data contract between teststop and AI agents.
//
// The Scenario schema is a stability boundary: once published in v0.1,
// changes to it are breaking changes for every downstream agent that
// consumes teststop output. Treat additions as additive only — never
// rename or remove fields without a major version bump.
package scenario

import "time"

// Priority signals how aggressively a failure of this scenario
// should block a deploy.
type Priority string

const (
	PriorityCritical Priority = "critical"
	PriorityHigh     Priority = "high"
	PriorityMedium   Priority = "medium"
	PriorityLow      Priority = "low"
)

// Scenario describes a single adversarial-user test situation as
// generated by an AI given the teststop mandate.
type Scenario struct {
	ScenarioID       string   `json:"scenario_id"`
	Title            string   `json:"title"`
	UserPerspective  string   `json:"user_perspective"`
	Preconditions    []string `json:"preconditions"`
	Steps            []string `json:"steps"`
	ChaosFactors     []string `json:"chaos_factors"`
	ExpectedBehavior string   `json:"expected_behavior"`
	FailureModes     []string `json:"failure_modes"`
	Priority         Priority `json:"priority"`
	ConfidenceArea   string   `json:"confidence_area"`
	IsEdgeCase       bool     `json:"is_edge_case"`
}

// Result is the outcome of running a generated scenario. In v0.1
// scenarios are not executed automatically — Result exists so agents
// or humans can record verdicts back into memory.
type Result struct {
	ScenarioID string    `json:"scenario_id"`
	Passed     bool      `json:"passed"`
	Notes      string    `json:"notes,omitempty"`
	RunAt      time.Time `json:"run_at"`
}
