package scenario

// Scenario is generated by AI and consumed by agents. STABLE after v0.1.
type Scenario struct {
	ScenarioID       string   `json:"scenario_id"`
	Title            string   `json:"title"`
	UserPerspective  string   `json:"user_perspective"`
	Preconditions    []string `json:"preconditions"`
	Steps            []string `json:"steps"`
	ChaosFactors     []string `json:"chaos_factors"`
	ExpectedBehavior string   `json:"expected_behavior"`
	FailureModes     []string `json:"failure_modes"`
	Priority         string   `json:"priority"` // critical | high | medium | low
	ConfidenceArea   string   `json:"confidence_area"`
	IsEdgeCase       bool     `json:"is_edge_case"`

	// Exec is an OPTIONAL v0.2 additive extension. When the AI can map a scenario
	// to a concrete, machine-executable request it emits an exec block, enabling
	// deterministic execution. Prose-only scenarios (no exec) remain fully valid
	// and are executed via the AI-driven or static path. omitempty keeps legacy
	// v0.1 JSON (no exec field) parsing unchanged.
	Exec *ExecSpec `json:"exec,omitempty"`
}

// ExecSpec describes how to deterministically execute a scenario. Optional (v0.2).
type ExecSpec struct {
	Mode           string            `json:"mode,omitempty"`            // "http" | "cli"
	Method         string            `json:"method,omitempty"`          // HTTP verb (GET, POST, ...)
	Path           string            `json:"path,omitempty"`            // appended to the run --target base URL
	Headers        map[string]string `json:"headers,omitempty"`         // HTTP request headers
	Body           string            `json:"body,omitempty"`            // HTTP request body
	ExpectedStatus int               `json:"expected_status,omitempty"` // 0 = "any non-5xx is a pass"
	Command        []string          `json:"command,omitempty"`         // CLI mode argv
	ExpectedExit   int               `json:"expected_exit,omitempty"`   // CLI mode expected exit code

	// Concurrency, when > 1, fires N identical HTTP requests simultaneously and
	// asserts the system yields exactly one winner (the rest cleanly rejected).
	// Used to verify race guards (double-submit, claim-the-last-item, etc.).
	Concurrency int `json:"concurrency,omitempty"`
}

// ExecMode values for ExecSpec.Mode.
const (
	ExecHTTP = "http"
	ExecCLI  = "cli"
)

const (
	PriorityCritical = "critical"
	PriorityHigh     = "high"
	PriorityMedium   = "medium"
	PriorityLow      = "low"
)
