package scenario

// Scenario is generated by AI and consumed by agents. STABLE after v0.1.
type Scenario struct {
	ScenarioID       string   `json:"scenario_id"`
	Title            string   `json:"title"`
	UserPerspective  string   `json:"user_perspective"`
	Preconditions    []string `json:"preconditions"`
	Steps            []string `json:"steps"`
	ChaosFactors     []string `json:"chaos_factors"`
	ExpectedBehavior string   `json:"expected_behavior"`
	FailureModes     []string `json:"failure_modes"`
	Priority         string   `json:"priority"` // critical | high | medium | low
	ConfidenceArea   string   `json:"confidence_area"`
	IsEdgeCase       bool     `json:"is_edge_case"`
}

const (
	PriorityCritical = "critical"
	PriorityHigh     = "high"
	PriorityMedium   = "medium"
	PriorityLow      = "low"
)
